# # .travis.yml
# language: node_js   #前端工程所以是JavaScript，编译环境是node_js
# node_js:
# - lts/* # 指定最新版本
# branchs:
#   only:
#   - master  #指定只有检测到master分支有变动时才执行任务
# install:
#   - npm install
# script:
#   - npm run build
# # deploy:
# #   provider: pages
# #   skip-cleanup: true
# #   keep-history: true
# #   local-dir: ./docs/.vuepress/dist
# #   target_branch: gh-pages
# #   on:
# #     branch: master
# #   github-token: $GITHUB_TOKEN

# after_script:
# #  - cd ./public
# #  - git init
#   - git config user.name "gattia"
#   - git config user.email "gattia.su@gmail.com"
# #  - git add .
# #  - git commit -m "Update docs"
# #  - git push --force --quiet "${Travis}@${GH_REF}" master:master
#   - sed -i "s/Travis/${Travis}/g" ./_config.yml
#   - hexo deploy


language: node_js
node_js:
    - lts/* # 指定最新版本
install:
    - npm install
script:
    - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master