# # .travis.yml
# language: node_js   #前端工程所以是JavaScript，编译环境是node_js
# node_js:
# - lts/* # 指定最新版本
# branchs:
#   only:
#   - master  #指定只有检测到master分支有变动时才执行任务
# install:
#   - npm install
# script:
#   - npm run build
# # deploy:
# #   provider: pages
language: node_js
node_js:
    - lts/* # 指定最新版本
install:
    - npm install
script:
    - npm run build
    - echo $GITHUB_TOKEN
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  local-dir: docs/.vuepress/dist
  on:
    branch: master
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable