# .travis.yml
language: node_js   #前端工程所以是JavaScript，编译环境是node_js
node_js:
- '10.15.3'   #指定node版本
branchs:
  only:
  - master  #指定只有检测到master分支有变动时才执行任务
install:
  - npm install
script:
  - npm run d
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  local-dir: .vuepress/dist
  on:
    branch: master
  github-token: $GITHUB_TOKEN